services:
  frontend-svc:
    build: ../../apps/url-shortner/frontend/
    ports:
      - "5173:5173"    
  shorten-svc:
    build: ../../apps/url-shortner/backend/shorten-svc
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIRECT_SVC=http://localhost:80
    depends_on:
      - redis

  redirect-svc:
    build: ../../apps/url-shortner/backend/redirect-svc
    ports:
      - "80:80"
    environment:
      - REDIS_HOST=redis
      - LISTEN_PORT=80
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    restart: always
    ports:
      - ":6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
