name: containarization-demo-example-iii
services:
  react-app:
    image:  alexjoy1992/demo_react_app:v2
    network_mode: host

  nginx-app:
    image:  nginx:latest
    network_mode: host

  whoami:
    image: traefik/whoami
    container_name: whoami-server
    environment:
      - WHOAMI_PORT_NUMBER=8082
    network_mode: host