services:
  app:
    image: nginx:latest
    ports:
      - "8080:8080"
    configs:
      - source: app_config
        target: /app/config.yml
    secrets:
      - source: db_pass
        target: /app/secrets.yml
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=mydb
      - POSTGRES_PASSWORD=supersecurepassword123

configs:
  app_config:
    file: ./config.yml 

secrets:
  db_pass:
    file: ./db_password.txt 

networks:
  containerization_demo:
    external: true
