services:
  shorten-svc:
    build: ../../apps/url-shortner/shorten-svc
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIRECT_SVC=http://localhost:90
    depends_on:
      - redis

  redirect-svc:
    build: ../../apps/url-shortner/redirect-svc
    ports:
      - "90:90"
    environment:
      - REDIS_HOST=redis
      - LISTEN_PORT=90
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    restart: always
    ports:
      - ":6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
