services:
  writer:
    build: ../../apps/writer
    restart: always
    volumes:
      - ./writer-data:/app/tmp
  redis:
    image: "redis:latest"
    restart: always
    ports:
      - ":6379"
    volumes:
      - ./redis_data:/data
